Update Kotlin to 2.1.20 in `jte-runtime-cp-test-models-gradle-kotlin-versionmismatch`, keeping JTE using 2.1.10.
The project now fails with `Caused by: java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.incremental.IncrementalCompilationFeatures.<init>(boolean, boolean, boolean, boolean, boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)'`

The build also contains the warning:
w: The artifact `org.jetbrains.kotlin:kotlin-compiler-embeddable` is present in the build classpath along Kotlin Gradle plugin.
This may lead to unpredictable and inconsistent behavior.
Please remove the `org.jetbrains.kotlin:kotlin-compiler-embeddable` artifact from the build classpath.
See https://kotl.in/gradle/internal-compiler-symbols for more details.